trigger:
- none

pool:
  vmImage: 'windows-latest'
  
steps:
- task: Ant@1
  inputs:
    buildFile: 'build - build.xml'
    options: 
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
- task: CmdLine@2
  inputs:
    script:
      cd D:\a\1\s\results\html
      dir
      powershell -command "\"$(Get-Content build.xml)\"> report.html"